### ISSUE TITLE
Issue with building ROS2 package, unable to properly source /opt/ros/foxy/setup.bash

### ISSUE THREAD

**Issue by jh-chng** [deitry/vscode-colcon-helper#25]
Hi,

I would like to apologize first as I am new to VScode and a little unsure on how to use your extension. That said, I am getting a build error in vscode, using your extension (ctrl+shift+p and 'Colcon: Build Current Package'): 

`> Executing task: colcon build --symlink-install --packages-select cpp_pubsub <

Starting >>> cpp_pubsub
--- stderr: cpp_pubsub
CMake Error at CMakeLists.txt:19 (find_package):
  By not providing "Findament_cmake.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "ament_cmake", but CMake did not find one.

  Could not find a package configuration file provided by "ament_cmake" with
  any of the following names:

    ament_cmakeConfig.cmake
    ament_cmake-config.cmake

  Add the installation prefix of "ament_cmake" to CMAKE_PREFIX_PATH or set
  "ament_cmake_DIR" to a directory containing one of the above files.  If
  "ament_cmake" provides a separate development package or SDK, be sure it
  has been installed.

---
Failed   <<< cpp_pubsub [0.05s, exited with code 1]

Summary: 0 packages finished [0.14s]
  1 package failed: cpp_pubsub
  1 package had stderr output: cpp_pubsub
The terminal process "colcon 'build', '--symlink-install', '--packages-select', 'cpp_pubsub'" terminated with exit code: 1.`

This seems to be due to /opt/ros/foxy/setup.bash not being sourced. However, following your instructions, I added the following in my package workspace/.vscode/settings.json:

`{
    "colcon.provideTasks": true,
    "colcon.globalSetup": ["/opt/ros/foxy/setup.sh"],
    "colcon.workspaceSetup":[
        "install/setup.sh"
    ],
}`

On my terminal, I am able to colcon build the package as per normal, after I source the ros bash script.
May I ask what have I been doing wrong? Or did I skip a step somewhere.

**Comment by deitry** [comment]
I apologize for not seeing this question in time.

Did you run ctrl+shift+p > `Colcon: Refresh Environment` command before running build? It generates `${workspace}/.vscode/colcon.env` file and then sourcing this environment so further build should see necessary variables. If you don't have `${workspace}/.vscode/colcon.env` file or it is empty, probably you should run `Refresh Environment` command.

**Comment by smith-doug** [comment]
I had the same problem.  I looked at the plugin's debug output and saw "Current shell is null".  Adding `"terminal.integrated.shell": "/usr/bin/bash"` fixed it.

**Comment by deitry** [comment]
Since https://github.com/deitry/vscode-colcon-helper/commit/52e18fdc876d4a6940ff2e14c5fca508111092f2 you may use `colcon.shell` setting if yours `terminal.integrated.shell` is empty or if you want to keep it different.

I'm closing this issue since there is no updates. Please reopen if you still encounter this issue.
