### ISSUE TITLE
colcon build Support for ROS2 in Windows 

### ISSUE THREAD

**Issue by arunj088** [deitry/vscode-colcon-helper#26]
when performing colcon build task in Windows, error is thrown and the reason being that the command is not executed from 'x64 Native tools Command Prompt for Visual Studio'. I am interested in seeing a way to address this in VSCode

error on colcon build task 
```VisualStudioVersion is not set, please run within a Visual Studio Command Prompt.```

**Comment by deitry** [comment]
Actually I never tested it on Windows, so I'm not surprised it's not working.

Will try to look on it

**Comment by deitry** [comment]
Maybe this is same issue?
https://answers.ros.org/question/317475/ros2-windows10-colcon-build-fails-on-ros2_example_ws-tutorial/

> On Windows, to use Visual Studio from the command-line you need to be in a "visual studio environment".

**Comment by flynneva** [comment]
im trying to get this extension running on windows as well. ill keep digging into it but let me know if either of you find a solution!

**Comment by flynneva** [comment]
I have found if you build the workspace first from a Visual Studio Developer terminal first, then try to run the `colcon build` task within VS code you get a different error than the one above:

```
CMake Error at C:/opt/ros/foxy/x64/share/rmw_implementation/cmake/rmw_implementation-extras.cmake:54 (message):
  The RMW implementation has been specified as 'rmw_fastrtps_dynamic_cpp' via
  environment variable 'RMW_IMPLEMENTATION', but it is not available at this
  time.
```

it builds fine using the Visual Studio Developer terminal....just not in VS Code.

i have tried to set VS Code to use the developer terminal by adding this to the `settings.json` file after finding it in File >Preferences > Terminal > Integrated > Shell > Windows:

```
"terminal.integrated.shell.windows": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Auxiliary\\Build\\vcvars64.bat"
```

**Comment by flynneva** [comment]
just for complete-ness...ill also include other parameters i've tried to play with in the `settings.json` file. nothing seems to fix the issue...and to be honest i dont really know what the issue is. I cant tell if the `colcon build` task in the vs code extension is actually sourcing the underlay correctly....i think it is but again im not sure. 

```
    "colcon.outputLog": true,
    "colcon.outputLevel": "info",
    "colcon.rosInstallPath.windows": "C:\\opt\\ros\\${version}\\x64\\bin",
    "colcon.globalSetup": [
        "C:\\opt\\ros\\foxy\\x64\\local_setup.bat"
    ],
    "colcon.workspaceSetup": [
        "install\\local_setup.bat"
    ],
    "colcon.refreshOnStart": true,
    "colcon.refreshOnTasksOpened": true,
    "colcon.refreshOnConfigurationChanged": true,
```

**Comment by deitry** [comment]
Actually I couldn't make ROS2 run on my system at all, even without VSCode. Simple `ros2 --help` or just `ros2` returns "failed to create process". Maybe I missed something in the installation steps or there is something in my usual configuration.

Maybe I should try to install it on VM, but my PC not that much fast, and debugging will be much slower that way

**Comment by deitry** [comment]
As of issue, you may want to play with manual variables resolution in the `.vscode/colcon.env` file.

**Comment by arunj088** [comment]
> Actually I couldn't make ROS2 run on my system at all, even without VSCode. Simple `ros2 --help` or just `ros2` returns "failed to create process". Maybe I missed something in the installation steps or there is something in my usual configuration.
> 
> Maybe I should try to install it on VM, but my PC not that much fast, and debugging will be much slower that way

@deitry I have seen that error with debug binaries installation of ROS2. Tried the release binaries variant of ROS2 and that error was gone in my system.  Alternate will be building ROS2 from source in windows

**Comment by deitry** [comment]
I'm getting this error with release binaries :(

But you may be right and I should rebuild it from source.

Upd. Issue was with python installation. I had multiple versions installed, while ROS expects certain version in certain location: https://docs.ros.org/en/foxy/Installation/Windows-Install-Binary.html#install-python

**Comment by deitry** [comment]
Finally I made colcon work (not ROS2, but that's enough).

It seems script I run to get envronment variables is not working under cmd/powershell, so variables simple are not processed.
I'm working on it

**Comment by flynneva** [comment]
I installed ROS2 binaries via choco and that worked for me (after installing all the dependencies).

excited to see if we can get this extension functional on windows! Would be great to see. Let me know if I can help out testing at all.

**Comment by flynneva** [comment]
Microsoft IoT website has separate install instructions than the main ROS2 docs.

https://ms-iot.github.io/ROSOnWindows/GettingStarted/SetupRos2.html

**Comment by deitry** [comment]
Just published 1.1.0 version. Please check it
https://marketplace.visualstudio.com/items?itemName=deitry.unity-debug

Copy-paste from CHANGELOG.md:

Please, note that currently you must use `cmd` as shell for running colcon tasks.

If you want to keep your settings for integrated shell, like `pwsh`, you can use new `colcon.shell` configuration setting
to specify which shell to use when running colcon tasks.

Also you must include Visual Studio batch file in your setup to run tasks in build environment.
For example:

```json
"colcon.workspaceSetup": [
    "C:\\ros2\\foxy\\local_setup.bat",
    "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat",
    "install/setup.bat"
],
```

**Comment by arunj088** [comment]
@deitry I tried the new version, Colcon build is getting executed but I end up getting error during the install phase. I see that the `--symlink-install' option is provided by default when we run the build task. Is there a way to override this flag .i.e, not use it. I tried building the packages outside VScode and whenever I pass the --symlink-install flag, I get the error. Maybe its an issue with the package that I am building, but it will be nice to have that feature.

**Comment by arunj088** [comment]
Just an update, seems like we need to be using cmd as administrator to run the --symlink-install option. Tried to run VSCode as administrator and the build was successful :). Wanted to highlight it here if thinking of any improvements. I think this issue can be closed!

**Comment by deitry** [comment]
@arunj088 You may open VS Code command promt, run `> Tasks: Configure Task` and then select `colcon: build task` in picker. Build task configuration should then appear in `tasks.json`, where you can remove `--symlink-install` argument.

I will keep this issue open until research a bit why symlinking not working. It seems that `mklink` in the `cmd` [should work without Admin rights](https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/) in Windows 10 since Creators Update, but I don't know what exact command `colcon` uses to make symlinks.

**Comment by deitry** [comment]
Just to mention, I discovered a way to run `colcon build` within `powershell`. See it in a new section of README.md:
https://github.com/deitry/vscode-colcon-helper#how-to-use-on-windows

**Comment by deitry** [comment]
Also I did a double-check about `--symlink-install`, mine setup is working even within Powershell without Admininstator rights.

```powershell
    Directory:  D:\prog\ros2test\install\examples_rclcpp_minimal_action_client\lib\examples_rclcpp_minimal_action_client

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
la---        2021-04-11     10:21        0   action_client_member_functions.exe
la---        2021-04-11     10:21        0   action_client_not_composable_with_cancel.exe
la---        2021-04-11     10:21        0   action_client_not_composable_with_feedback.exe
la---        2021-04-11     10:21        0   action_client_not_composable.exe
```

I believe, this [is available since](https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/) some Win10 version. I'm using Windows 10 20H2 + PowerShell 7.1.3 + Visual Studio Community 2019 16.9.2 (`msbuild -version` returns 16.9.0.11203)
