### ISSUE TITLE
Can't run colcon

### ISSUE THREAD

**Issue by roncapat** [deitry/vscode-colcon-helper#32]
Ubuntu 20.04 ROS2 Foxy

After enabling, refreshing and running colcon build task, i get the following:

```
> Executing task in folder ros2_ws: /home/roxy/ros2_ws/colcon build <

The terminal process failed to launch: Path to shell executable "/home/roxy/ros2_ws/colcon" does not exist.

Terminal will be reused by tasks, press any key to close it.
```

I don't get why the extension is searching for colcon executable in the workspace itself...

**Comment by deitry** [comment]
I believe it is related to https://github.com/deitry/vscode-colcon-helper/commit/0daf8b6af16be0a75f56c5f865594abcc89ccfad#diff-f3abdc65f84ec5bd6292be5a6bbf0578d73569adc8baa3b301f3c39229548cf8R180

I do not work with ROS over year so I didn't check this accurately.
As workaround you may try to see output of `which colcon` and put that into `colcon.colconExe` in workspace or global VS Code settings.

I'll check this and try to fix it.

**Comment by roncapat** [comment]
I already tried to put the full path in the settings, but the override does not work. It seems to be uneffective.

**Comment by roncapat** [comment]
Any updates? @deitry
